name: run main.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *" # Run every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        env:
          ORGANISATION: ${{ secrets.ORGANISATION }}
          ORGANISER: ${{ secrets.ORGANISER }}
          CALENDAR_CATEGORIES: ${{ secrets.CALENDAR_CATEGORIES }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_PATH: ${{ secrets.FTP_REMOTE_PATH }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
